apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: ergosanitas
  name: ergosanitas-service
spec:
  ports:
  - name: "5173"
    port: 5173
    protocol: TCP
    targetPort: 5173
  selector:
    app: ergosanitas-service
  type: NodePort
status:
  loadBalancer: {}
