name: Ergosanitas CI

on:
  push:
    branches:
      - main  # Cambia esto si usas otra rama para producción

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar el repositorio
        uses: actions/checkout@v3

      - name: Configurar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'  # Asegúrate de que sea compatible con tu proyecto

      - name: Instalar dependencias
        run: npm install --legacy-peer-deps

      - name: Construir la aplicación
        run: npm run build

      - name: Subir archivos a cPanel vía FTP
        uses: SamKirkland/FTP-Deploy-Action@4.3.0
        with:
          server: ftp.ergosanitas.com
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: dist/  
          server-dir: /public_html/mi_react_app/