name: Ergosanitas CI

on:
  push:
    branches:
      - main  # Cambia esto si usas otra rama para producción

concurrency:
  # Define un grupo de concurrencia basado en la referencia de la rama
  group: ci-${{ github.ref }}
  # Cancela cualquier ejecución anterior en progreso para esta rama
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest

#    strategy:
#      matrix:
#        node-version: [18.x,20.x,22.x]    

    steps:
      - name: Clonar el repositorio
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22.x
          cache: 'npm'

      - name: Instalar dependencias
        run: npm install --legacy-peer-deps

      - name: Construir la aplicación
        run: npm run build

      - name: Verificar carpeta de build
        run: ls -la dist/

      - name: Subir archivos con lftp
        run: |
          apt-get install -y lftp
          lftp -u "${{ secrets.FTP_USERNAME }},${{ secrets.FTP_PASSWORD }}" ftp.ergosanitas.com <<EOF
          set ftp:ssl-allow no
          set net:max-retries 5
          set net:timeout 60
          set mirror:parallel-transfer-count 1
          set ftp:passive-mode on
          mkdir -p /public_html/mi_react_app/{files/gallery,files/images}
          mirror -R dist/ /public_html/mi_react_app/
          quit
          EOF
      